# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "A command-line tool to detect and prevent drift between your code and your documentation."
  homepage "https://github.com/driftee-ai/drift"
  version "0.1.34"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/driftee-ai/drift/releases/download/v0.1.34/drift_0.1.34_Darwin_x86_64.tar.gz"
      sha256 "9777f48ac386c0d9fffe8307895a0b2ad009a6da31eddeb8d73e6041ae4fb03e"

      def install
        bin.install "drift"
      end
    end
    on_arm do
      url "https://github.com/driftee-ai/drift/releases/download/v0.1.34/drift_0.1.34_Darwin_arm64.tar.gz"
      sha256 "ed90d8599204af2d7e5a85b885bb3819940d80840512c1922ac08315c9780162"

      def install
        bin.install "drift"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/driftee-ai/drift/releases/download/v0.1.34/drift_0.1.34_Linux_x86_64.tar.gz"
        sha256 "79f0835124d0e64278243cc3cf0e37ee220149500dca8253b6a5f6d3f9d8d96a"

        def install
          bin.install "drift"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/driftee-ai/drift/releases/download/v0.1.34/drift_0.1.34_Linux_arm64.tar.gz"
        sha256 "28f983a8133c2717baab405110cc1ae72c59cb42ed8ffa9a5beb2f5347263737"

        def install
          bin.install "drift"
        end
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
