# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "A command-line tool to detect and prevent drift between your code and your documentation."
  homepage "https://github.com/driftee-ai/drift"
  version "0.4.8"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/driftee-ai/drift/releases/download/v0.4.8/drift_0.4.8_Darwin_x86_64.tar.gz"
      sha256 "a68c667e7d71bf6b87d7dac9b316d9a98b753e3d8620ab6161900a5deca8f65a"

      def install
        bin.install "drift"
      end
    end
    on_arm do
      url "https://github.com/driftee-ai/drift/releases/download/v0.4.8/drift_0.4.8_Darwin_arm64.tar.gz"
      sha256 "baf2c0f20536c6e00acbb7a640a0fb75eb346ed46036ba9f2e059a5ee42e932b"

      def install
        bin.install "drift"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/driftee-ai/drift/releases/download/v0.4.8/drift_0.4.8_Linux_x86_64.tar.gz"
        sha256 "cea9840fa70b071b1f2ffdf8ea0dd71ae5ed1b49bdff67183d8b89e21020980e"

        def install
          bin.install "drift"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/driftee-ai/drift/releases/download/v0.4.8/drift_0.4.8_Linux_arm64.tar.gz"
        sha256 "eed2b2300731f257ab3ebbe4622068a4457ff440689e9a7be78b3fa3ec7428ca"

        def install
          bin.install "drift"
        end
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
